### ISSUE TITLE
error on 1.21

### ISSUE THREAD

**Issue by TerslenK** [TheBlackEntity/AntiPluginLookUp#1] opened 2024-07-01 16:39 UTC
[16:38:22 ERROR]: [me.entity303.antipluginlookup.olderversions.TabBlocker_Reflections_New] null
java.lang.RuntimeException: Couldn't find PlayerConnection field! (Modded environment?)
        at AntiPluginLookUp-2.0.0.jar/me.entity303.antipluginlookup.olderversions.TabBlocker_Reflections_New.lambda$FetchPlayerConnectionField$1(TabBlocker_Reflections_New.java:69) ~[AntiPluginLookUp-2.0.0.jar:?]
        at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at AntiPluginLookUp-2.0.0.jar/me.entity303.antipluginlookup.olderversions.TabBlocker_Reflections_New.FetchPlayerConnectionField(TabBlocker_Reflections_New.java:69) ~[AntiPluginLookUp-2.0.0.jar:?]
        at AntiPluginLookUp-2.0.0.jar/me.entity303.antipluginlookup.olderversions.TabBlocker_Reflections_New.Inject(TabBlocker_Reflections_New.java:39) ~[AntiPluginLookUp-2.0.0.jar:?]
        at AntiPluginLookUp-2.0.0.jar/me.entity303.antipluginlookup.olderversions.JoinListener.OnLogin(JoinListener.java:23) ~[AntiPluginLookUp-2.0.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor39.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-38-1f5db50]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-38-1f5db50]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-38-1f5db50]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1408) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1415) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[paper-1.21.jar:1.21-38-1f5db50]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-38-1f5db50]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:38:22 INFO]: SagoFani2024 joined the game

**Comment by Test-Account666** [comment] 2024-07-01 17:23
Thanks for the info ^^

Will fix this as soon as possible

**Comment by okunamayanad** [comment] 2024-07-05 22:02
> Thanks for the info ^^
> 
> Will fix this as soon as possible

Is there any update on this? Did you find the cause? If so is there any ETA for this? It looks like plugin works just fine but spams the console

**Comment by Test-Account666** [comment] 2024-07-07 10:22
> > Thanks for the info ^^
> > Will fix this as soon as possible
> 
> Is there any update on this? Did you find the cause? If so is there any ETA for this? It looks like plugin works just fine but spams the console

Should be fixed in 2.0.1 :)

**Closed as completed by Test-Account666** 2024-07-07 10:22 UTC
